# Generated by Django 2.1.3 on 2018-11-15 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('album_name', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('album_popularity', models.IntegerField(blank=True, null=True)),
                ('album_type', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('genres', models.CharField(blank=True, max_length=100, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('artist_popularity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('play_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.CharField(max_length=50)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=100)),
                ('song_popularity', models.IntegerField(blank=True, null=True)),
                ('danceability', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('key', models.IntegerField(blank=True, null=True)),
                ('loudness', models.FloatField(blank=True, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('speechiness', models.FloatField(blank=True, null=True)),
                ('acousticness', models.FloatField(blank=True, null=True)),
                ('instrumentalness', models.FloatField(blank=True, null=True)),
                ('liveness', models.FloatField(blank=True, null=True)),
                ('valence', models.FloatField(blank=True, null=True)),
                ('tempo', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('time_signature', models.IntegerField(blank=True, null=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spytify.Album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spytify.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spytify.Song'),
        ),
        migrations.AddField(
            model_name='play',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spytify.UserProfile'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spytify.Artist'),
        ),
    ]
