# Generated by Django 2.0.7 on 2018-07-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('album_popularity', models.IntegerField()),
                ('album_type', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100)),
                ('followers', models.IntegerField()),
                ('artist_popularity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('play_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=100)),
                ('song_popularity', models.IntegerField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.IntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('duration_ms', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spytify.Album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spytify.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('date_joined', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spytify.Song'),
        ),
        migrations.AddField(
            model_name='play',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spytify.User'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spytify.Artist'),
        ),
    ]
