# Generated by Django 2.0.7 on 2018-11-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spytify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_popularity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_popularity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='device',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='acousticness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='danceability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration_ms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='energy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='instrumentalness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='liveness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='loudness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='mode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_popularity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='speechiness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='tempo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='time_signature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='valence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
