# Generated by Django 2.0.7 on 2019-01-23 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spytify', '0002_auto_20181114_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
                ('token_type', models.CharField(blank=True, max_length=50, null=True)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=200, null=True)),
                ('expires_at', models.IntegerField(blank=True, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
