# Generated by Django 2.0.7 on 2018-11-04 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spytify', '0003_auto_20181103_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='song_id',
            new_name='song',
        ),
    ]
